---
- hosts: iot

  tasks:

  - name: Set the hostname
    hostname:
      name: web01

  - name: Set authorized key took from url
    authorized_key:
      user: pi
      state: present
      key: https://github.com/michielgerritsen.keys

  - name: Add repository source
    become: yes
    become_method: sudo
    apt_repository:
      repo: deb http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free
      state: present

  - name: execute apt-key update
    become: yes
    become_method: sudo
    shell: apt-key update

  - name: Update apt cache
    become: yes
    become_method: sudo
    apt:
      update_cache: yes

  - name: gpg add key
    become: yes
    become_method: sudo
    shell: gpg --keyserver pgpkeys.mit.edu --recv-key CCD91D6111A06851

  - name: apt-key add
    become: yes
    become_method: sudo
    shell: gpg --armor --export CCD91D6111A06851 | sudo apt-key add -

  - name: execute apt-key update
    become: yes
    become_method: sudo
    shell: apt-get update

  - name: install packages
    become: yes
    become_method: sudo
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - php7.1-cli
      - php7.1-curl
      - php7.1-fpm
      - php7.1-intl
      - php7.1-json
      - php7.1-mcrypt
      - php7.1-sqlite3
      - sqlite3

  - name: ensure php7.1-fpm cgi.fix_pathinfo=0
    lineinfile: dest=/etc/php/7.1/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    lineinfile: dest=/etc/php/7.1/cli/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    become: yes
    become_method: sudo
    notify:
      - restart php7.1-fpm
      - restart nginx

  - name: enable php7.1 mcrypt module
    shell: phpenmod mcrypt
    become: yes
    become_method: sudo
    args:
      creates: /etc/php/7.1/cli/conf.d/20-mcrypt.ini

  handlers:
    - name: restart php7.1-fpm
      service: name=php7.1-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
